# Generated by Django 3.2 on 2023-06-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.IntegerField(primary_key=True, serialize=False)),
                ('timezoneStr', models.CharField(default='America/Chicago', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PollingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_Monitoring.store')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time_local', models.TimeField(blank=True, null=True)),
                ('end_time_local', models.TimeField(blank=True, null=True)),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_Monitoring.store')),
            ],
        ),
    ]
